server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking}
    username: ${SPRING_DATASOURCE_USERNAME:banking}
    password: ${SPRING_DATASOURCE_PASSWORD:banking123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.banking: DEBUG
