server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: transaction-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://nexabank-prod-sqlsvr.database.windows.net:1433;database=banking;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:bankingadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:NexaBank@2024!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
services:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:https://nexabank-prod-account-service.azurewebsites.net}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:https://nexabank-prod-notification-service.azurewebsites.net}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.banking: DEBUG